# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fface4560295dad234fcb2535d5c6922d88dd92223f51ee0cfc58610877b768e591a22d73337fce83a2e6ad6b7bf423eee86003c19fd8e785c81bcfddf7b672c

test:
  secret_key_base: f5d95e30c9058ea836db61987713830097c3f392544026959c53be6080dfefbcb1f70c5baa3a16b52ff64ef630238e2da80b4326e6cf6c1bd91a98f457d9e4c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
